### ISSUE TITLE
ANSI layout PCB

### ISSUE THREAD

**Issue by roundtree** [javiverdu/Keensy#2]
Hi,

Would you be able to create the PCB in ANSI layout? Or otherwise be able to share the 3D design source file of the PCB, so I can try to modify it? Or was it entirely generated through the PCB generator?

Awesome project by the way, can't wait to start printing it!

**Comment by javiverdu** [comment]
Hi,

I'm glad you like Keensy so much. The PCB was indeed generated and modified in a CAD program and I can tell you that this method is not worth it, the PCB doesn't feel good enough and there is at least 1 switch not making contact everytime
(it really is a pain in the ass).

The reason why it still exists in the proyect is because it "works" and I invested a lot of time in it. Right now the best method is making a real PCB ISO/ANSI with hotswap soldered switches compatibility (I'm working on it!)

If you want to make it from scratch I recommend you making it handwired using insulated copper wires or magnet wires, this is way less tedious than dealing with normal cables.

Cheers.

**Comment by roundtree** [comment]
All right, thanks for the info! I'll look for a different path then. At least thanks for the inspiration, and keep up the good work!
